import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LoadingProvider } from "./providers/LoadingProvider";
import "./globals.css";
import 'antd/dist/reset.css';
import './row.css'
import WrapperProvider from "@/provider/wrapperprovider";
import Script from "next/script";
import { ErrorBoundary } from 'react-error-boundary';
import ErrorFallback from './components/ErrorFallback';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
           <Script
            src="https://telegram.org/js/telegram-web-app.js"
            strategy="beforeInteractive"
          />
          <Script src="//whephiwums.com/vignette.min.js" data-zone="9103912" data-sdk='show_9103912'/>

        <ErrorBoundary FallbackComponent={ErrorFallback}>
          <LoadingProvider>
            <WrapperProvider>
              {children}
            </WrapperProvider>
          </LoadingProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
